" vim:fdm=marker:ts=4:sw=4:et:
"        _
" __   _(_)_ __ ___  _ __ ___
" \ \ / / | '_ ` _ \| '__/ __|
"  \ V /| | | | | | | | | (__
"   \_/ |_|_| |_| |_|_|  \___|
"
" Mark's .vimrc
"-----------------------------
" Section: Key Mappings {{{1
"------------------------------------------------------------------------------
nmap \e :NERDTreeToggle<CR>
nmap \t :set expandtab tabstop=4 shiftwidth=4 softtabstop=4<CR>
nmap \T :set expandtab tabstop=8 shiftwidth=8 softtabstop=4<CR>
nmap \r :TagbarToggle<CR>

"" buffa flippin'
map <C-e> :e#<CR>
map <C-n> :bnext<CR>
map <C-p> :bprev<CR>

nnoremap <space> za
nnoremap <CR> za
vnoremap <space> zf

" Section: Plugin settings {{{1
"------------------------------------------------------------------------------
let mapleader = ","
let maplocalleader = ","

" vimspell.vim
let spell_auto_type = ""


runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
execute pathogen#helptags()

" NERD_tree.vim
let NERDTreeIgnore = ['\~$', '\.pyc$']

" Syntastic
let g:syntastic_enable_signs=1
let g:syntastic_auto_jump=0
let g:syntastic_stl_format = '[%E{Err: %fe #%e}%B{, }%W{Warn: %fw #%w}]'

" Ctrlp.vim
let g:ctrlp_map = '<Leader>t'
let g:ctrlp_match_window_bottom = 0
let g:ctrlp_match_window_reversed = 0
let g:ctrlp_working_path_mode = 0
let g:ctrlp_dotfiles = 0
let g:ctrlp_switch_buffer = 0
nmap ; :CtrlPBuffer<CR>

filetype plugin indent on



" Section: Color and syntax {{{1
"------------------------------------------------------------------------------

syntax on
set background=dark

" Helper to initialize Zenburn colors in 256-color mode.
function! ColorTermZenburn()
    let g:zenburn_high_Contrast=1
    let g:zenburn_disable_Label_underline=1
    colorscheme zenburn
    highlight normal ctermbg=234
    highlight SpecialKey cterm=NONE ctermfg=235 ctermbg=None
endfunction

function! ColorTermSolarized()
    let g:solarized_termcolors=256
    let g:solarized_contrast="high"
    let g:solarized_termtrans=1
    colorscheme solarized
    highlight SpecialKey cterm=NONE ctermfg=235 ctermbg=None
endfunction

" Highlight trailing whitespace with garish color
function! HighlightExtraWhitespace()
    highlight ExtraWhitespace ctermfg=red
    match ExtraWhitespace /\s\+$/
    highlight SpecialKey ctermbg=None
endfunction


if !has('gui_running')
    if $TERM == "xterm-256color" || $TERM == "screen-256color" || $COLORTERM == "gnome-terminal"
        set t_Co=256
        call ColorTermZenburn()
        "call ColorTermSolarized()
        call HighlightExtraWhitespace()
    elseif has("terminfo")
        colorscheme default
        set t_Co=8
        set t_Sf=[3%p1%dm
        set t_Sb=[3%p1%dm
    else
        colorscheme default
        set t_Co=8
        set t_Sf=[3%dm
        set t_Sb=[3%dm
    endif
endif



" Resume previous position in buffer when opened
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END

" Additional syntax modes
autocmd BufRead,BufNewFile *.frag,*.vert,*.vp,*.fp,*glsl set filetype=glsl

" Section: Vim options {{{1
"------------------------------------------------------------------------------
set ts=4
set sw=4
set autoindent                      " Carry over indenting from previous line
set autoread                        " Auto read when a file changes
set backspace=indent,eol,start
set cindent

silent! set foldmethed=marker       " Use braces by default
set hlsearch                        " Highlight searching
set ignorecase                      " Case insensitive
set incsearch                       " Search as you type
set infercase                       " Completion recognizes capitalization
set list                            " Show invisible characters in listchars
set listchars=tab:→\ ,trail:←,extends:»,precedes:«
set smartcase
set showmatch                       " Hilight matching braces/parens/etc.
set laststatus=2                    " So powerline shows up
set scrolloff=15                    " Keep cursor away from this many chars top/bottom
set scroll=4
set nobackup

" Section: Load ~/.vimlocal {{{1
"------------------------------------------------------------------------------
source ~/.vimlocal
