#           _
#   _______| |__
#  |_  / __| '_ \
#   / /\__ \ | | |
#  /___|___/_| |_|
#

# Prezto!
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Antigen
if [[ -s "${HOME}/.dotfiles/zsh/antigen" ]]; then
  source "${HOME}/.dotfiles/zsh/antigen/antigen.zsh"
  antigen apply
fi

# My scripts
if [[ -d $HOME/.dotfiles/zsh/scripts ]]; then
  for config_file ($HOME/.dotfiles/zsh/scripts/*.zsh) source $config_file
fi

#/// functions

# Fancy ctrl-z (thanks, Adam Stankiewicz!)
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
    zle redisplay
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

updot () {
  pushd
  cd ~/.dotfiles
  git stash
  git pull --rebase
  git stash pop
  git pull --recurse-submodules=on-demand
  popd
}


#/// My local bin
export PATH=$HOME/bin:$PATH

#/// npm bin
export PATH=$HOME/node_modules/.bin:$PATH

#/// Go
export GOPATH=$HOME/go
export PATH=$PATH:$HOME/go/bin

#/// Libvirt
export LIBVIRT_DEFAULT_URI="qemu:///system"

#/// misc exports
export EDITOR=vim
export VISUAL=$EDITOR
export XDG_CONFIG_HOME=$HOME/.config

#/// aliases aplenty
alias wallpaper="feh --bg-fill -z"
alias svim="EDITOR=vim sudoedit"
alias gulp="node_modules/.bin/gulp"
alias scp="noglob scp"
alias capesc="setxkbmap -option caps:escape"
alias rsync="noglob rsync"
alias genie-local="~/code/GENie/bin/linux/genie"
alias lights="~/ouimeaux/bin/wemo switch 'WeMo Switch' toggle"

#/// fuzzy finder config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
