#!/bin/sh
HOSTNAME=$(cat /etc/hostname)
TARGET_DIR=/tmp/i3-$USER
I3_CONFIG_GLOBAL=~/.dotfiles/i3/config.all
I3_CONFIG_HOST=~/.dotfiles/i3/config.${HOSTNAME}
I3_CONFIG_TARGET=$TARGET_DIR/config
I3STATUS_TARGET=$TARGET_DIR/i3status

if [[ ! -e $TARGET_DIR ]]; then
	mkdir -p $TARGET_DIR
fi

# Generate i3config
if [[ ! -e $I3_CONFIG_TARGET || $I3_CONFIG_HOST -nt $I3_CONFIG_TARGET || $I3_CONFIG_GLOBAL -nt $I3_CONFIG_TARGET ]]; then
	if [[ -e $I3_CONFIG_HOST ]]; then
		cat $I3_CONFIG_GLOBAL $I3_CONFIG_HOST > $I3_CONFIG_TARGET
	else
		echo $I3_CONFIG_GLOBAL
		cp $I3_CONFIG_GLOBAL $I3_CONFIG_TARGET
	fi
fi

# Generate i3status
if [[ -e ~/.dotfiles/i3/i3status.${HOSTNAME} ]]; then
	I3STATUS_SOURCE=~/.dotfiles/i3/i3status.${HOSTNAME}
else
	I3STATUS_SOURCE=~/.dotfiles/i3/i3status.default
fi

if [[ -x $I3STATUS_SOURCE ]]; then
	exec $I3STATUS_SOURCE > $I3STATUS_TARGET
elif [[ $I3STATUS_SOURCE -nt $I3STATUS_TARGET ]]; then
	cp $I3STATUS_SOURCE $I3STATUS_TARGET
fi

